
export interface MunicipalityRecord {
    department: string;
    municipality: string;
}

export const municipalityMap: Record<string, MunicipalityRecord> = {
    "001": { department: "Managua", municipality: "Managua" },
    "002": { department: "Managua", municipality: "San Rafael del Sur" },
    "003": { department: "Managua", municipality: "Tipitapa" },
    "004": { department: "Managua", municipality: "Mateare" },
    "005": { department: "Managua", municipality: "San Francisco Libre" },
    "006": { department: "Managua", municipality: "Villa Carlos Fonseca" },
    "007": { department: "Managua", municipality: "El Crucero" },
    "008": { department: "Managua", municipality: "Ciudad Sandino" },
    "009": { department: "Managua", municipality: "Ticuantepe" },
    "010": { department: "Jinotega", municipality: "Wiwilí de Jinotega" },
    "011": { department: "Jinotega", municipality: "El Cuá" },
    "012": { department: "Jinotega", municipality: "San José de Bocay" },
    "015": { department: "Jinotega", municipality: "Santa María de Pantasma" },
    "020": { department: "Jinotega", municipality: "San Rafael del Norte" },
    "025": { department: "Jinotega", municipality: "San Sebastián de Yalí" },
    "030": { department: "Jinotega", municipality: "La Concordia" },
    "035": { department: "Jinotega", municipality: "Jinotega" },
    "040": { department: "Matagalpa", municipality: "Rancho Grande" },
    "041": { department: "Carazo", municipality: "Jinotepe" },
    "045": { department: "Matagalpa", municipality: "El Tuma - La Dalia" },
    "050": { department: "Matagalpa", municipality: "San Isidro" },
    "055": { department: "Matagalpa", municipality: "Sébaco" },
    "060": { department: "Matagalpa", municipality: "Matagalpa" },
    "065": { department: "Matagalpa", municipality: "San Ramón" },
    "070": { department: "Matagalpa", municipality: "Matiguás" },
    "075": { department: "Matagalpa", municipality: "Muy Muy" },
    "080": { department: "Matagalpa", municipality: "Esquipulas" },
    "085": { department: "Matagalpa", municipality: "San Dionisio" },
    "090": { department: "Matagalpa", municipality: "Terrabona" },
    "095": { department: "Matagalpa", municipality: "Ciudad Darío" },
    "096": { department: "Matagalpa", municipality: "Río Blanco" },
    "100": { department: "Boaco", municipality: "San José de los Remates" },
    "105": { department: "Boaco", municipality: "Boaco" },
    "110": { department: "Boaco", municipality: "Camoapa" },
    "115": { department: "Boaco", municipality: "Santa Lucía" },
    "120": { department: "Boaco", municipality: "Teustepe" },
    "125": { department: "Boaco", municipality: "San Lorenzo" },
    "130": { department: "Chontales", municipality: "Comalapa" },
    "135": { department: "Chontales", municipality: "Juigalpa" },
    "140": { department: "Chontales", municipality: "La Libertad" },
    "145": { department: "Chontales", municipality: "Santo Domingo" },
    "150": { department: "Chontales", municipality: "Santo Tomás" },
    "155": { department: "Chontales", municipality: "San Pedro de Lóvago" },
    "160": { department: "Chontales", municipality: "Acoyapa" },
    "165": { department: "Chontales", municipality: "Villa Sandino" },
    "170": { department: "Chontales", municipality: "El Coral" },
    "175": { department: "Chontales", municipality: "San Francisco de Cuapa" },
    "180": { department: "Granada", municipality: "Diriá" },
    "185": { department: "Granada", municipality: "Diriomo" },
    "190": { department: "Granada", municipality: "Granada" },
    "195": { department: "Granada", municipality: "Nandaime" },
    "200": { department: "Carazo", municipality: "San Marcos" },
    "205": { department: "Carazo", municipality: "Dolores" },
    "210": { department: "Carazo", municipality: "Diriamba" },
    "215": { department: "Carazo", municipality: "El Rosario" },
    "220": { department: "Carazo", municipality: "La Paz de Carazo" },
    "225": { department: "Carazo", municipality: "Santa Teresa" },
    "230": { department: "Carazo", municipality: "La Conquista" },
    "235": { department: "Rivas", municipality: "Altagracia" },
    "240": { department: "Rivas", municipality: "Belén" },
    "245": { department: "Rivas", municipality: "Buenos Aires" },
    "250": { department: "Rivas", municipality: "Cárdenas" },
    "255": { department: "Rivas", municipality: "Moyogalpa" },
    "260": { department: "Rivas", municipality: "Potosí" },
    "265": { department: "Rivas", municipality: "Rivas" },
    "270": { department: "Rivas", municipality: "San Jorge" },
    "275": { department: "Rivas", municipality: "San Juan del Sur" },
    "280": { department: "Rivas", municipality: "Tola" },
    "285": { department: "Río San Juan", municipality: "El Almendro" },
    "290": { department: "Río San Juan", municipality: "El Castillo" },
    "295": { department: "Río San Juan", municipality: "Morrito" },
    "300": { department: "Río San Juan", municipality: "San Carlos" },
    "305": { department: "Río San Juan", municipality: "San Juan del Norte" },
    "310": { department: "Río San Juan", municipality: "San Miguelito" },
    "315": { department: "Masaya", municipality: "Catarina" },
    "320": { department: "Masaya", municipality: "La Concepción" },
    "325": { department: "Masaya", municipality: "Masatepe" },
    "330": { department: "Masaya", municipality: "Masaya" },
    "335": { department: "Masaya", municipality: "Nandasmo" },
    "340": { department: "Masaya", municipality: "Nindirí" },
    "345": { department: "Masaya", municipality: "Niquinohomo" },
    "350": { department: "Masaya", municipality: "San Juan de Oriente" },
    "355": { department: "Masaya", municipality: "Tisma" },
    "360": { department: "Nueva Segovia", municipality: "Jalapa" },
    "365": { department: "Nueva Segovia", municipality: "Murra" },
    "370": { department: "Nueva Segovia", municipality: "El Jícaro" },
    "375": { department: "Nueva Segovia", municipality: "San Fernando" },
    "380": { department: "Nueva Segovia", municipality: "Mozonte" },
    "385": { department: "Nueva Segovia", municipality: "San Juan de Río Coco" },
    "390": { department: "Nueva Segovia", municipality: "Dipilto" },
    "395": { department: "Nueva Segovia", municipality: "Macuelizo" },
    "400": { department: "Nueva Segovia", municipality: "Santa María" },
    "405": { department: "Nueva Segovia", municipality: "Ocotal" },
    "410": { department: "Nueva Segovia", municipality: "Ciudad Antigua" },
    "415": { department: "Nueva Segovia", municipality: "Quilalí" },
    "420": { department: "Nueva Segovia", municipality: "Wiwilí de Nueva Segovia" },
    "425": { department: "Madriz", municipality: "Somoto" },
    "430": { department: "Madriz", municipality: "Totogalpa" },
    "435": { department: "Madriz", municipality: "Telpaneca" },
    "440": { department: "Madriz", municipality: "San Juan de Río Coco (Madriz)" },
    "445": { department: "Madriz", municipality: "Palacagüina" },
    "450": { department: "Madriz", municipality: "Yalagüina" },
    "455": { department: "Madriz", municipality: "San Lucas" },
    "460": { department: "Madriz", municipality: "Las Sabanas" },
    "465": { department: "Madriz", municipality: "San José de Cusmapa" },
    "470": { department: "Estelí", municipality: "Pueblo Nuevo" },
    "475": { department: "Estelí", municipality: "Condega" },
    "480": { department: "Estelí", municipality: "Estelí" },
    "485": { department: "Estelí", municipality: "San Juan de Limay" },
    "490": { department: "Estelí", municipality: "La Trinidad" },
    "495": { department: "Estelí", municipality: "San Nicolás" },
    "500": { department: "Chinandega", municipality: "Cinco Pinos" },
    "505": { department: "Chinandega", municipality: "San Pedro del Norte" },
    "510": { department: "Chinandega", municipality: "San Francisco del Norte" },
    "515": { department: "Chinandega", municipality: "Santo Tomás del Norte" },
    "520": { department: "Chinandega", municipality: "Villanueva" },
    "525": { department: "Chinandega", municipality: "Somotillo" },
    "530": { department: "Chinandega", municipality: "El Viejo" },
    "535": { department: "Chinandega", municipality: "Puerto Morazán" },
    "540": { department: "Chinandega", municipality: "Chinandega" },
    "545": { department: "Chinandega", municipality: "Corinto" },
    "550": { department: "Chinandega", municipality: "El Realejo" },
    "555": { department: "Chinandega", municipality: "Chichigalpa" },
    "560": { department: "Chinandega", municipality: "Posoltega" },
    "565": { department: "León", municipality: "Achuapa" },
    "570": { department: "León", municipality: "El Sauce" },
    "575": { department: "León", municipality: "Santa Rosa del Peñón" },
    "580": { department: "León", municipality: "El Jicaral" },
    "585": { department: "León", municipality: "Larreynaga" },
    "590": { department: "León", municipality: "Telica" },
    "595": { department: "León", municipality: "Quezalguaque" },
    "600": { department: "León", municipality: "León" },
    "605": { department: "León", municipality: "La Paz Centro" },
    "610": { department: "León", municipality: "Nagarote" },
    "615": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "Kukra Hill" },
    "620": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "Laguna de Perlas" },
    "625": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "Desembocadura del Río Grande" },
    "630": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "El Tortuguero" },
    "635": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "La Cruz de Río Grande" },
    "640": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "Paiwas" },
    "645": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "Rama" },
    "650": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "El Ayote" },
    "655": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "Muelle de los Bueyes" },
    "660": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "Corn Island" },
    "665": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "Bluefields" },
    "670": { department: "Región Autónoma de la Costa Caribe Sur", municipality: "Nueva Guinea" },

    "675": { department: "Región Autónoma de la Costa Caribe Norte", municipality: "Bonanza" },
    "680": { department: "Región Autónoma de la Costa Caribe Norte", municipality: "Mulukukú" },
    "685": { department: "Región Autónoma de la Costa Caribe Norte", municipality: "Prinzapolka" },
    "690": { department: "Región Autónoma de la Costa Caribe Norte", municipality: "Puerto Cabezas (Bilwi)" },
    "695": { department: "Región Autónoma de la Costa Caribe Norte", municipality: "Rosita" },
    "700": { department: "Región Autónoma de la Costa Caribe Norte", municipality: "Siuna" },
    "705": { department: "Región Autónoma de la Costa Caribe Norte", municipality: "Waslala" },
    "710": { department: "Región Autónoma de la Costa Caribe Norte", municipality: "Waspán" }

};
